/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDJvNvnCvS4aEUCZ7EvKS1g",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-6506f10e",
            securityGroupIds: [
                "sg-035cfbbdeafd7bcb0"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-a02ebadb",
                    availabilityZone: "ap-south-1c"
                },
                {
                    subnetId: "subnet-4f233f27",
                    availabilityZone: "ap-south-1a"
                },
                {
                    subnetId: "subnet-141a5758",
                    availabilityZone: "ap-south-1b"
                }
            ]
        }
    }
}).schema({
    "employer_referrals": a.model({
        id: a.integer().required(),
        referral_code: a.string().required(),
        expiry: a.string().required(),
        is_active: a.boolean().required(),
        created_at: a.string().required(),
        updated_at: a.string().required(),
        employer_id: a.integer().required()
    }).identifier([
        "id"
    ]),
    "referred_users": a.model({
        id: a.integer().required(),
        company_domain: a.string().required(),
        is_active: a.boolean().required(),
        created_at: a.string().required(),
        updated_at: a.string().required(),
        referral_id: a.integer().required(),
        referred_user_id: a.integer().required()
    }).identifier([
        "id"
    ]),
});
